#undef CHECK_ESCAPE_IMPL_GET_MASK
//
#undef LOAD_U
#undef LOAD_A
#undef SET_ALL
#undef VECTOR_TYPE_U
#undef VECTOR_TYPE
#undef READ_UNSIGNED_BIT_NAME
#undef CHECK_COUNT_MAX
#undef READ_512_MASK_TYPE
#undef READ_BIT_SIZEx8
#undef READ_BIT_SIZEx4
#undef READ_BIT_SIZEx2
#undef READ_BIT_SIZE
#undef _FROM_TYPE
