#include "pyyjson.h"
//
#include "s_in.inl.h"
#include "w_in.inl.h"

// #if COMPILE_SIMD_BITS == 512
// #    define _WVECx2_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 1024, A)
// #    define _WVECx4_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 2048, A)
// #    define _WVECx2_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 1024, U)
// #    define _WVECx4_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 2048, U)
// #    define _WVEC_half_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 256, A)
// #    define _WVEC_half_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 256, U)
// #elif COMPILE_SIMD_BITS == 256
// #    define _WVECx2_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 512, A)
// #    define _WVECx4_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 1024, A)
// #    define _WVECx2_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 512, U)
// #    define _WVECx4_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 1024, U)
// #    define _WVEC_half_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 128, A)
// #    define _WVEC_half_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 128, U)
// #else
// #    define _WVECx2_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 256, A)
// #    define _WVECx4_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 512, A)
// #    define _WVECx2_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 256, U)
// #    define _WVECx4_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 512, U)
// #    define _WVEC_half_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 64, A)
// #    define _WVEC_half_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 64, U)
// #endif
