#include "w_out.inl.h"
/*
 * Macros IN
 */
#if COMPILE_WRITE_UCS_LEVEL == 4
#    define _WRITER U32_WRITER
#    define _TARGET_TYPE u32
#    define WRITE_BIT_SIZE 32
#    define WRITE_SUPPORT_MASK_WRITE (SIMD_BIT_SIZE >= 256)
#    define READ_512_MASK_TYPE u16
#elif COMPILE_WRITE_UCS_LEVEL == 2
#    define _WRITER U16_WRITER
#    define _TARGET_TYPE u16
#    define WRITE_BIT_SIZE 16
#    define WRITE_SUPPORT_MASK_WRITE (SIMD_BIT_SIZE > 256)
#    define READ_512_MASK_TYPE u32
#elif COMPILE_WRITE_UCS_LEVEL == 1
#    define _WRITER U8_WRITER
#    define _TARGET_TYPE u8
#    define WRITE_BIT_SIZE 8
#    define WRITE_SUPPORT_MASK_WRITE (SIMD_BIT_SIZE > 256)
#    define READ_512_MASK_TYPE u64
#else
#    error "COMPILE_WRITE_UCS_LEVEL must be 1, 2 or 4"
#endif

#define WRITE_BATCH_COUNT (SIMD_BIT_SIZE / 8 / sizeof(_TARGET_TYPE))
#define WRITE_UNSIGNED_BIT_NAME PYYJSON_SIMPLE_CONCAT2(U, WRITE_BIT_SIZE)
#define _WVEC_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, SIMD_BIT_SIZE, A)
#define _WVEC_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, SIMD_BIT_SIZE, U)
#if SIMD_BIT_SIZE == 512
#    define _WVECx2_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 1024, A)
#    define _WVECx4_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 2048, A)
#elif SIMD_BIT_SIZE == 256
#    define _WVECx2_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 512, A)
#    define _WVECx4_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 1024, A)
#else
#    define _WVECx2_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 256, A)
#    define _WVECx4_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 512, A)
#endif
