#include "w_out.inl.h"
#include "unicode/unicode_buffer.h"

/*
 * Macros IN
 */
#if COMPILE_WRITE_UCS_LEVEL == 4
#    define _WRITER U32_WRITER
#    define _TARGET_TYPE u32
#    define WRITE_BIT_SIZE 32
#    define WRITE_SUPPORT_MASK_WRITE (SIMD_BIT_SIZE >= 256)
#    define READ_512_MASK_TYPE u16
#elif COMPILE_WRITE_UCS_LEVEL == 2
#    define _WRITER U16_WRITER
#    define _TARGET_TYPE u16
#    define WRITE_BIT_SIZE 16
#    define WRITE_SUPPORT_MASK_WRITE (SIMD_BIT_SIZE > 256)
#    define READ_512_MASK_TYPE u32
#elif COMPILE_WRITE_UCS_LEVEL == 1
#    define _WRITER U8_WRITER
#    define _TARGET_TYPE u8
#    define WRITE_BIT_SIZE 8
#    define WRITE_SUPPORT_MASK_WRITE (SIMD_BIT_SIZE > 256)
#    define READ_512_MASK_TYPE u64
#else
#    error "COMPILE_WRITE_UCS_LEVEL must be 1, 2 or 4"
#endif

#define WRITE_BATCH_COUNT (SIMD_BIT_SIZE / 8 / sizeof(_TARGET_TYPE))
#define WRITE_UNSIGNED_BIT_NAME PYYJSON_SIMPLE_CONCAT2(U, WRITE_BIT_SIZE)
#define _WVEC_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, SIMD_BIT_SIZE, A)
#define _WVEC_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, SIMD_BIT_SIZE, U)
#if SIMD_BIT_SIZE == 512
#    define _WVECx2_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 1024, A)
#    define _WVECx4_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 2048, A)
#    define _WVECx2_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 1024, U)
#    define _WVECx4_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 2048, U)
#elif SIMD_BIT_SIZE == 256
#    define _WVECx2_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 512, A)
#    define _WVECx4_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 1024, A)
#    define _WVECx2_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 512, U)
#    define _WVECx4_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 1024, U)
#else
#    define _WVECx2_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 256, A)
#    define _WVECx4_A_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 512, A)
#    define _WVECx2_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 256, U)
#    define _WVECx4_U_ PYYJSON_CONCAT4(VECTOR, WRITE_UNSIGNED_BIT_NAME, 512, U)
#endif

/*
 * Reserve space for the unicode buffer.
 */
#define UNICODE_BUFFER_RESERVE PYYJSON_CONCAT2(unicode_buffer_reserve, COMPILE_WRITE_UCS_LEVEL)

force_inline bool UNICODE_BUFFER_RESERVE(EncodeUnicodeBufferInfo *unicode_buffer_info, Py_ssize_t size);

#define WRITE_UNICODE_U64 PYYJSON_CONCAT2(write_unicode_u64, COMPILE_WRITE_UCS_LEVEL)
#define WRITE_UNICODE_F64 PYYJSON_CONCAT2(write_unicode_f64, COMPILE_WRITE_UCS_LEVEL)
