#undef read_inf_or_nan
#undef _read_nan
#undef _read_inf
#undef _read_null
#undef _read_false
#undef _read_true
#undef read_to_hex
#undef verify_escape_hex
#undef DecodeSrcInfo
#undef cmpeq_2chars
//
#undef READ_UNSIGNED_BIT_NAME_UPPER
#undef READ_UNSIGNED_BIT_NAME
#undef AVX512_BITMASK_TYPE
#undef READ_BIT_SIZEx8
#undef READ_BIT_SIZEx4
#undef READ_BIT_SIZEx2
#undef READ_BIT_SIZE
#undef _src_t
