#undef MAKE_RW_NAME
#undef ELEVATE_128_DST_T
#undef ELEVATE_128_SRC_T
#undef VECTOR_ELEVATE_128
#undef VECTOR_ELEVATE4
#undef SIMD_SUB_TYPE
#undef WR_DIV
#include "r_out.inl.h"
#include "w_out.inl.h"
