name: "ASAN Check"
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - "CMakeLists.txt"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        token: '${{ secrets.ACTION_GITHUB_TOKEN }}'
    - name: Install nix
      uses: cachix/install-nix-action@master
      with:
        github_access_token: '${{ secrets.ACTION_GITHUB_TOKEN }}'
    - name: Setup cachix
      uses: cachix/cachix-action@master
      with:
        name: antares0982
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: run asan_check.sh
      run: |
        nix develop -c dev_tools/asan_check.sh
