name: "ASAN Check"
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - "CMakeLists.txt"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install nix
      uses: cachix/install-nix-action@master
    - name: Setup cachix
      uses: cachix/cachix-action@master
      with:
        name: antares0982
    - name: Run asan check
      run: |
        nix develop -c python ./dev_tools/automated_test.py --all-ver --asan
