name: "Build Check"
on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"

jobs:
  BUILD-CHECK:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pyver: ["9", "10", "11", "12", "13", "14"]
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install nix
      uses: cachix/install-nix-action@master
    - name: Setup cachix
      uses: cachix/cachix-action@master
      with:
        name: antares0982
    - name: Run build
      run: |
        nix develop -c python ./dev_tools/automated_test.py --pyver ${{ matrix.pyver }} --build-only
