name: "Run Test"
on:
  workflow_dispatch:
  push:
    branches:
      - "dev"
    paths:
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"

jobs:
  RUN-TEST:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pyver: ["9", "10", "11", "12", "13", "14"]
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install nix
      uses: cachix/install-nix-action@master
    - name: Setup cachix
      uses: cachix/cachix-action@master
      with:
        name: antares0982
    - name: Build and Run Tests
      run: |
        nix develop -c python ./dev_tools/automated_test.py --pyver ${{ matrix.pyver }} --ignore bench
    - name: Test Release Build
      run: |
        nix develop -c python ./dev_tools/automated_test.py --build-only --pyver ${{ matrix.pyver }} --build-type Release
