name: "Run Test"
on:
  workflow_dispatch:
  push:
    branches:
      - "dev"
    paths:
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"

jobs:
  RUN-TEST:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pyver: ["9", "10", "11", "12", "13", "14"]
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install nix
      uses: cachix/install-nix-action@master
    - name: Setup cachix
      uses: cachix/cachix-action@master
      with:
        name: antares0982
    - name: Test Release Build
      run: |
        nix develop -c python ./dev_tools/automated_test.py --build-only --pyver ${{ matrix.pyver }} --build-type Release
    - name: Build and Run Python Tests (DEBUG)
      run: |
        nix develop -c python ./dev_tools/automated_test.py --build-type Debug --pyver ${{ matrix.pyver }}
    - name: Print Features
      run: |
        PYTHONPATH=$(pwd)/build-py3.${{ matrix.pyver }} .nix-pyenv/bin/python3.${{ matrix.pyver }} -c "import pyyjson;pyyjson.print_current_features()"
    - name: Run Python Tests (SDE, AVX512)
      run: |
        PYTHONPATH=$(pwd)/build-py3.${{ matrix.pyver }} .nix-pyenv/bin/run-sde-clx .nix-pyenv/bin/python3.${{ matrix.pyver }} -m pytest --random-order python-test
    - name: Run Python Tests (SDE, AVX2)
      run: |
        PYTHONPATH=$(pwd)/build-py3.${{ matrix.pyver }} .nix-pyenv/bin/run-sde-rpl .nix-pyenv/bin/python3.${{ matrix.pyver }} -m pytest --random-order python-test
    - name: Run C Tests (SDE, ALL)
      run: |
        PYTHONPATH=$(pwd)/build-py3.${{ matrix.pyver }} .nix-pyenv/bin/run-sde-clx ./build-py3.${{ matrix.pyver }}/pyyjson_test
